# Generated by Django 6.0.1 on 2026-01-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccountCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('username', models.CharField(default='demo')),
                ('password', models.CharField(default='demo')),
            ],
        ),
    ]
