# Generated by Django 6.0.1 on 2026-01-14 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleslot',
            unique_together={('user', 'day', 'period')},
        ),
    ]
