# Generated by Django 6.0.1 on 2026-01-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_scheduleslot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslot',
            name='subject',
            field=models.CharField(default='[ placeholder ]', max_length=200),
        ),
    ]
