# Generated by Django 6.0.1 on 2026-01-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pendingwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwork',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
