# Generated by Django 6.0.1 on 2026-01-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pendingwork_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslot',
            name='subject',
            field=models.CharField(default='[placeholder]', max_length=200),
        ),
    ]
